# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='checklist',
            field=models.BinaryField(default='False'),
        ),
    ]
